//Module nba
export const SET_NBA_TEAM_LIST = 'SET_NBA_TEAM_LIST';
//Module sports
export const SET_SPORTS_SELECTED_TYPE = 'SET_SPORTS_SELECTED_TYPE';
export const SET_SPORTS_SELECTED_COUNTRY = 'SET_SPORTS_SELECTED_COUNTRY';
export const CLEAR_SPORTS_SELECTED_TYPE = 'CLEAR_SPORTS_SELECTED_TYPE';
export const CLEAR_SPORTS_SELECTED_COUNTRY = 'CLEAR_SPORTS_SELECTED_COUNTRY';
export const CLEAR_SPORTS_SELECTED_ALL = 'CLEAR_SPORTS_SELECTED_ALL';

export const SET_SPORTS_QUERY_PARAMS = 'SET_SPORTS_QUERY_PARAMS'
export const SET_SPORTS_QUERY_RESULT = 'SET_SPORTS_QUERY_RESULT'
export const CLEAR_SPORTS_QUERY_RESULT = 'CLEAR_SPORTS_QUERY_RESULT'
export const SET_SPORTS_PAGE_RESULT = 'SET_SPORTS_PAGE_RESULT'
export const SET_SPORTS_PAGE_TOTAL = 'SET_SPORTS_PAGE_TOTAL'

//Module premierLeague
export const SET_PREMIER_LEAGUE_PLAYER = 'SET_PREMIER_LEAGUE_PLAYER'